name: jenga_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.12
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  firebase_auth_web: ^5.15.3
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
  http: ^1.4.0
  image_picker: ^1.1.2
  js_interop: ^0.0.1
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_paypal_payment: ^1.0.6
  webview_flutter: ^4.7.0
  url_launcher: ^6.3.2
  flutter_markdown: ^0.7.7+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/content/
    - .env
    # - assets/icons/
    # - assets/fonts/
