// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDge8EA8uf-VAje83FqOlDfDytLnhC8QwU',
    appId: '1:73754095414:web:f7694800d5ecadbd2e8d97',
    messagingSenderId: '73754095414',
    projectId: 'jenga-app-d24fb',
    authDomain: 'jenga-app-d24fb.firebaseapp.com',
    storageBucket: 'jenga-app-d24fb.firebasestorage.app',
    measurementId: 'G-9SQPP1X8WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSnlYnSUCZRDDhCZKnhDeQu1z8tNhR6KY',
    appId: '1:73754095414:android:22ee10a33314d3272e8d97',
    messagingSenderId: '73754095414',
    projectId: 'jenga-app-d24fb',
    storageBucket: 'jenga-app-d24fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGZ8yIuNTA3wwlvMoHcLDTShdIKtMe3qs',
    appId: '1:73754095414:ios:7870d6533944ae1d2e8d97',
    messagingSenderId: '73754095414',
    projectId: 'jenga-app-d24fb',
    storageBucket: 'jenga-app-d24fb.firebasestorage.app',
    iosBundleId: 'com.example.jengaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGZ8yIuNTA3wwlvMoHcLDTShdIKtMe3qs',
    appId: '1:73754095414:ios:7870d6533944ae1d2e8d97',
    messagingSenderId: '73754095414',
    projectId: 'jenga-app-d24fb',
    storageBucket: 'jenga-app-d24fb.firebasestorage.app',
    iosBundleId: 'com.example.jengaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDge8EA8uf-VAje83FqOlDfDytLnhC8QwU',
    appId: '1:73754095414:web:12f83d9641711a802e8d97',
    messagingSenderId: '73754095414',
    projectId: 'jenga-app-d24fb',
    authDomain: 'jenga-app-d24fb.firebaseapp.com',
    storageBucket: 'jenga-app-d24fb.firebasestorage.app',
    measurementId: 'G-P3558KTCPE',
  );
}
